### ISSUE TITLE
Tutorial bug

### ISSUE THREAD

**Issue by dkuku** [hyperstack-org/website#29]
HI - very nice project. but I had a small issue with the external TodoMVC css file:
```css
.todo-list li .edit {
  display: none;
}
```
was hiding the element I wanted to edit - took me some time to debug it.
Changing it to `padding-left: 60px;` looks ok - I don't know if it's an upstream change or I messed something up in my code - but I even tried to copy and paste it from the tutorial so it should be ok
